
# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 신원석
title: 게임 클라이언트 개발자
email: onerpg3023@gmail.com
git: https://github.com/sinwonsuk
phone: 010-5383-2470

# Dark Mode (true/false/never)
darkmode: false

# About Me
about_profile_image: images/profile.jpg
about_content: |
   안녕하세요, 게임 클라이언트 개발자에 지원하는 신원석입니다. 저는 동료들과 지식을 공유하고, 함께 성장하는 과정을 소중하게 여깁니다. 앞으로는 더 나아가, 팀원들에게 멘토링을 제공하며 성장을 돕는 개발자가 되고 싶습니다.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        link: https://github.com/sinwonsuk
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
        description: |
          다양한 모작을 통해 게임의 시스템과 설계 원리를 깊이 이해하고, 실제 개발에 적용할 수 있는 기초 역량을 갖추게 되었습니다.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: (주)도은
        caption: 2018.01~2020.04
        description: |
          생산직에서 일하며 효율적인 작업 방식과 문제 해결 능력을 키웠으며, 팀워크와 책임감의 중요성을 배웠습니다.
          이를 통해 체계적인 업무 처리와 현장 대응력을 높일 수 있었습니다.

  - title: Education
    layout: list
    content:
      - layout: left
        title: 방송통신대학교
        caption: 재학 중
        description: |
          게임 개발 공부를 하다 보니 기초적인 부분에서 부족함을 느껴 방송통신대학교에 재학 중입니다.

  - title: A Little More About Me
    layout: text
    content: |
      게임 개발 외에도 다음과 같은 관심사와 취미가 있습니다:
      - 게임
      - 헬스
      - 노름

  - title: Cover Letter
    layout: text
    content: |
      **게임 개발 도전 계기**
      평소에도 게임을 좋아하긴 했지만 게임을 만드는 건 게임을 좋아하는 것과는 별개라 생각하여 마음속으로 묻어두기만 하고 생활하였습니다. 소방 설비 쪽 공부를 하며 면접 준비를 하고 있는 와중에 문득 내가 일 평생 해야 하는 직장인데 내가 좋아하는 일을 도전하지 않고 포기하는 건 아니라고 생각하여 준비하던 걸 포기하고 게임 쪽으로 할 수 있는 일을 알아보다 프로그래머라는 직업을 알게 되어 도전하게 되었습니다. 

      **프로그래머로서의 성장**
      여러 게임들을 모작 하면서 프로그래머 로서의 다양한 지식과 노하우를 쌓을 수 있었습니다. 처음 제작한 메탈 슬러그 라는 게임은 제가 게임 프로그래머 로서의 첫 단추를 끼우는 만큼 잘 만들고 싶었지만 생각처럼 쉽지 않았습니다. 메탈슬러그라는 게임은 리소스가 몸통과 다리가 따로 있어 리소스를 따로 합치거나 코드로 몸통과 다리의 랜더러의 포지션을 잘 적용시켜야 해서 작업량이 만만치 않았습니다. 처음에 툴을 만들어서 게임을 제작하려다 오히려 시간을 뺴앗기기도 하며 게임 만드는 게 생각보다 만만치 않다는 것을 알 수 있었습니다. 그래도 차근차근 엔진의 업데이트 구조와 비트맵, 2d 스프라이트 와 같은 게임의 기본 구조를 파악하면서 완성할 수 있었습니다. 그 이후로 메탈슬러그 게임을 교훈 삼아 이번엔 리소스가 잘 정리된 게임을 찾아봤더니 컵헤드라는 게임을 알게 되었고 이게임을 모작하게 되었습니다. 처음 모작할 땐 순조롭게 진행되었지만 뭔가 메모리 사용량이 너무 높아서 이유를 알아보니 jpg파일은 텍스쳐를 압축하지 않고 그대로 gpu에 담아서 메모리가 크다는 문제점을 파악했습니다. 처음 해결하려 한 방법은 jpg 파일 말고 dds 파일을 사용하여 문제를 해결하려 했으나 이미 프로젝트가 많이 진행되어 불가능하여 따로 Directx의 compress함수를 사용하여 텍스쳐를 압축하여 메모리 사용량을 절감할 수 있었습니다. 이 사건을 해결하면서 전반적인 엔진구조와 랜더링 과정을 좀 더 자세히 알게 되었습니다. 그 이후로 다크소울 3이라는 팀 프로젝트를 하게 되었습니다 이번 프로젝트의 목적은 3d 게임 개발의 경험과 팀 협업능력의 상승이라 생각했습니다. 팀원들과 빠르고 효율적인 소통을 위해 매주 월요일마다 회의를 하여 어떤 문제가 있고 진행은 어디까지 했는지 서로 이야기를 나누면서 프로젝트를 진행하였습니다. 제가 이 프로젝트에서 맡은 업무는 플레이어 제작이었습니다. 플레이어를 제작하면서 제가 어려웠던 건 생각보다 팀원들의 코드 스타일이 전부 다 다르다는 것이었습니다. 이         문제를 회의 시간에 이야기를 하게 되었고 사용한 방법은 baseActor이라는 클래스를 상속하여 필요한 변수나 함수들을 baseActor라는 클래스의 공유하는 방법을 사용했습니다. 그렇게 기본적인 엔진구조와 기초 지식을 쌓은 후 저는 상용엔진에 대해 배우고 싶다고 생각했습니다. 언리얼과 유니티가 있었지만 개인적으로 캐주얼한 게임을 만들어 보고 싶어 유니티를 선택하게 되었습니다. 한 달의 개인 공부를 끝마친 후 데이브 더 다이버라는 게임을 제작하게 되었고 이번엔 시간의 얽매이지 않고 코드를 좀 더 깔끔하게 짜고 싶었습니다. 그래서 다른 유니티 강의를 보며 기존의 짜던 코드에서 좀 더 좋아 보이면 바꾸는 식으로 게임을 제작하게 되었고 성공적으로 프로젝트를 완수할 수 있었습니다. 

      **장래 포부**
      저는 프로그래머로서의 성장뿐 아니라 동료의 인정을 가장 중요한 요소라고 생각합니다. 그 이유는 나 스스로의 가치를 증명하는 방법은 나의 업무를 완벽하게 해내는 것과 동료의 인정을 받는 것이라고 생각합니다. 그렇기에 저는 성장을 멈추지 않고 누구보다 이상적인 팀원이 되기 위해 노력하겠습니다.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
