# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 신원석
title: 게임 클라이언트 개발자
email: onerpg3023@gmail.com
git: https://github.com/sinwonsuk
phone: 010-5383-2470

# Dark Mode (true/false/never)
darkmode: false

# About Me
about_profile_image: images/profile.jpg

about_content: |
   안녕하세요, 게임 클라이언트 개발자에 지원하는 신원석입니다. 저는 동료들과 지식을 공유하고, 함께 성장하는 과정을 소중하게 여깁니다. 앞으로는 더 나아가, 팀원들에게 멘토링을 제공하며 성장을 돕는 개발자가 되고 싶습니다.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: 데이브 더 다이버
        caption: 2024.06~2024.09
        description: |    
          [https://github.com/sinwonsuk/Unity_Dave_The_Diver](https://github.com/sinwonsuk/Unity_Dave_The_Diver)<br>[유튜브 링크](https://youtu.be/rHRmZDMo6vE) 
      - layout: left
        title: 다크소울 3
        caption: 2023.12~2024.04
        description: |
          [https://github.com/chang-ha/DirectX_3DTeamPortfolio](https://github.com/chang-ha/DirectX_3DTeamPortfolio)<br>[유튜브 링크](https://www.youtube.com/watch?v=iqox7R0WdYM) 
      - layout: left
        title: 문라이터
        caption: 2023.09~2023.12
        description: |
          [https://github.com/sinwonsuk/Directx_Moonlight](https://github.com/sinwonsuk/Directx_Moonlight)<br>[유튜브 링크](https://youtu.be/Z_VltbQlJQ4) 
      - layout: left
        title: 컵헤드
        caption: 2023.04~2023.07
        description: |
          [https://github.com/sinwonsuk/Directx11_Cuphead](https://github.com/sinwonsuk/Directx11_Cuphead)<br>[유튜브 링크](https://youtu.be/EoADcLeIDLo) 
      - layout: left
        title: 메탈슬러그 2
        caption: 2023.02~2023.03
        description: |
          [https://github.com/sinwonsuk/Winapi_MetalSlug2](https://github.com/sinwonsuk/Winapi_MetalSlug2)<br>[유튜브 링크](https://youtu.be/i1kpW1eZXi4) 




      # - layout: top-middle
      #   link: https://github.com/sinwonsuk/Unity_Dave_The_Diver
      # - layout: top-middle
      #   link: https://github.com/chang-ha/DirectX_3DTeamPortfolio
      # - layout: top-middle
      #   link: https://github.com/sinwonsuk/Directx11_Cuphead
      # - layout: top-middle
      #   link: https://github.com/sinwonsuk/Directx_Moonlight
      # - layout: top-middle
      #   link: https://github.com/sinwonsuk/Winapi_MetalSlug2

  - title: Experience
    layout: list
    content:
      - layout: left
        title: (주)도은
        caption: 2018.01~2020.04
        description: |
          생산직에서 일하며 효율적인 작업 방식과 문제 해결 능력을 키웠으며, 팀워크와 책임감의 중요성을 배웠습니다.
          이를 통해 체계적인 업무 처리와 현장 대응력을 높일 수 있었습니다.

  - title: Education
    layout: list
    content:
      - layout: left
        title: 방송통신대학교
        caption: 재학 중
        description: |
          컴퓨터 과학과 재학중
      - layout: left
        title: 호서대학교
        caption: 2016.02~2017.08 
        description: |
          신소재 공학과 수료
       
  - title: Cover Letter
    layout: text   
    content: |
      - 자기소개    
       저는 목표를 설정하면 끝까지 이루기 위해 꾸준히 나아가는 사람입니다. 결심한 순간부터 더 이상 망설이지 않고, 문제를 해결하며 앞으로 전진합니다.

       어떤 일이든 먼저 시도해 보는 것을 중요하게 생각합니다. 예를 들어, 산업체에 취직하기로 결심했을 때, 당시 몸이 왜소하여 체력을 기르는 것이 먼저라고 판단했습니다. 꾸준한 운동을 통해  42kg  에  서   54kg까지 몸을 만들었고 정상 체중에 부족하지만, 어느 정도 목표를 달성했고 그 결과 산업체에 성공적으로 취업할 수 있었습니다.
       
       프로젝트가 원활하게 진행되지 않을 때, 저는 먼저 지금 해결해야 할 가장 중요한 문제는 무엇인지 자신에게 묻습니다. 복잡한 상황이 펼쳐지더라도, 핵심 문제를 파악하고 해결해 나가는 과정이   중  요 하  다고 믿습니다. 해결책을 찾는 과정에서 좌절할 때도 있지만, 그런 순간에도 흔들리지 않고 꾸준히 나아가려는 마음가짐이 저를 성장하게 합니다. 저는 실력을 하나하나 쌓아가면  목 표에  결 국  도달 할  수 있다고 확신하며, 작은 성과들이 쌓여 결국 큰 결과를 이룰 수 있다는 신념을 지니고 있습니다.
       
       저의 장점은 다양한 프로젝트 경험에서도 잘 발휘되었으며, 특히 예상치 못한 문제나 어려움이 발생했을 때 끈기와 문제 해결 능력으로 해결책을 찾아내고 성과를 이루어냈습니다


          
      - 문제 해결 능력
      
        게임을 만들다 보면 여러 가지 문제에 직면하게 됩니다. 그러한 상황에서 저는 문제 해결에만 집중합니다.
 
        데이브 더 다이버라는 게임을 만들 때 물고기들이 서로 겹치지 않으면서 움직임을 공유하되 장애물을 피하는 방법을 고안했어야 했습니다. 며칠을 버스에서 집에 가면서 고민했고 친구와 대화 하면서도 해결 방법을 생각해 내는 것만 집중했습니다.
        그러다 문득 인터넷을 통해 boids 알고리즘이라는 것을 알게 되었고 해결의 실마리를 얻게 된 저는 구현하는 것은 시간만 투자하면 완성할 수 있었습니다. 이러한 방법을 사용하여 프로젝트를 진행하고부터는 못 만드는 콘텐츠는 없다고 생각이 듭니다.

        이 경험을 통해 문제 해결 과정에서 중요한 것은 포기하지 않고 끝까지 해결책을 찾는 자세라는 것을 배웠습니다. 또한, 새로운 알고리즘이나 기술을 배우고 적용하는 과정에서 제 역량을 더욱 확장할 수 있었습니다. 앞으로도 다양한 프로젝트에서 마주하는 어려움 들을 해결하며 더 나은 개발자가 되기 위해 끊임없이 도전할 것입니다.
         
      - 의사소통 능력
      
         업무의 성공은 의사소통과 협업에서 비롯된다는 것을 실감하게 되었습니다.

          처음 3D 포트폴리오를 작업하기 전, 다른 팀들이 의사소통 문제나 실력 차이로 갈등을 겪는 모습을 보면서 팀 작업에 대한 고민이 많았습니다. 하지만 결국 팀 작업을 통해 더 높은 질의 결과물을 만들고, 팀 협업의 경험을 쌓아야겠다는 결심을 하게 되었습니다.

          어떻게 하면 원활한 진행이 가능할까에 대해 팀원들과 상의했고, 그 결과로 두 가지 중요한 규칙을 세우게 되었습니다. 첫 번째로 철저한 역할 분담을 통해 각자의 책임을 명확히 하는 것과 두 번째로 일주일에 한 번 회의를 진행해 각자의 진행 상황을 공유하고 문제를 해결하는 시간을 갖는 것입니다.

          회의는 단순한 진행 체크가 아닌 팀원들 간의 피드백과 협력을 통해 문제를 빠르게 해결하는 중요한 시간이 되었습니다. 이를 통해 개인의 역량을 더욱 강화할 수 있었고, 게임의 완성도와 질을 높이는 데 집중할 수 있었습니다.

          저희 팀의 특별한 규칙 중 하나는, 각 팀원이 회의에서 자신의 작업 일정에 대해 명확한 약속을 하는 것이었습니다. 이 약속을 통해 팀원들은 서로에 대한 신뢰를 쌓을 수 있었고, 이를 바탕으로 분쟁 없이 목표에 집중하며 원활하게 작업을 진행할 수 있었습니다.

          다양한 사람들과 의사소통하며 협력하는 과정에서 불화를 완전히 없애는 것은 어려울 수 있지만, 규칙과 약속을 통해 서로의 기대를 조율하고, 문제를 미리 해결하려는 노력을 통해 성공적인 협업을 이뤄낼 수 있었습니다.

      - 장래 포부 

        미래에는 클라이언트 업무뿐만 아니라 서버 개발에 대한 심층적인 학습을 통해 대규모 사용자들이 원활하게 접속하고 안정적으로 게임을 즐길 수 있는 환경을 구축하고 싶습니다. 이를 위해 서버 아키텍처와 데이터베이스 설계를 체계적으로 공부하고, 네트워크 프로그래밍의 기초부터 고급 기술까지 폭넓게 익힐 계획입니다.

        좀 더 먼 미래에는 제가 만든 게임이 많은 사람에게 즐거움과 감동을 줄 수 있는 작품이 되어, 업계에서 인정받는 개발자로 자리매김하고 게임이 오래도록 기억에 남는 경험이 되기를 희망합니다. 이러한 목표를 달성하기 위해 지속해서 기술을 연마하고 도전을 두려워하지 않겠습니다.




# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins: []
