# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 신원석
title: 게임 클라이언트 개발자
email: onerpg3023@gmail.com
git: https://github.com/sinwonsuk
phone: 010-5383-2470

# Dark Mode (true/false/never)
darkmode: false




# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 안녕하세요, 게임 클라이언트 개발자에 지원하는 신원석입니다. 저는 동료들과 지식을 공유하고, 함께 성장하는 과정을 소중하게 여깁니다. 앞으로는 더 나아가, 팀원들에게 멘토링을 제공하며 성장을 돕는 개발자가 되고 싶습니다.

 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        link: https://github.com/sinwonsuk
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >

        description: | # this will include new lines to allow paragraphs
         그동안 다양한 모작을 통해 게임의 시스템과 설계 원리를 깊이 이해하고, 실제 개발에 적용할 수 있는 기초 역량을 갖추게 되었습니다

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: (주)도은           
        caption: 2018.01~2020.04
        description: | # this will include new lines to allow paragraphs
            생산직에서 일하며 효율적인 작업 방식과 문제 해결 능력을 키웠으며, 팀워크와 책임감의 중요성을 배웠습니다.이를 통해 체계적인 업무 처리와 현장 대응력을 높일 수 있었습니다.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:    
    
      - layout: left
        title: 방송통신대학교
        caption: 재학중
        quote: >
        
        description: | # this will include new lines to allow paragraphs
         게임 개발 공부를 하다 보니 기초적인 부분의 부족함을 느껴 방송통신대학교를 다시 재학중 입니다.

     - layout: left
        title: 방송통신대학교
        caption: 재학중


 - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
     게임개발 외에도 다음과 같은 관심사와 취미가 있습니다.
      - 게임
      - 헬스
      - 노름      

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
